package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/tartale/kmttg-plus/go/pkg/model"
	"github.com/tartale/kmttg-plus/go/pkg/server"
	"github.com/tartale/kmttg-plus/go/pkg/tivo"
)

// Episodes is the resolver for the episodes field.
func (r *seriesResolver) Episodes(ctx context.Context, obj *model.Series) ([]*model.Episode, error) {
	return tivo.GetEpisodes(ctx, obj)
}

// Series returns server.SeriesResolver implementation.
func (r *Resolver) Series() server.SeriesResolver { return &seriesResolver{r} }

type seriesResolver struct{ *Resolver }
