package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/tartale/kmttg-plus/go/pkg/apicontext"
	"github.com/tartale/kmttg-plus/go/pkg/model"
	"github.com/tartale/kmttg-plus/go/pkg/server"
	"github.com/tartale/kmttg-plus/go/pkg/tivo"
)

// Shows is the resolver for the shows field.
func (r *tivoResolver) Shows(ctx context.Context, obj *model.Tivo, filter *model.ShowFilter, limit *int, offset *int) ([]model.Show, error) {
	ctx = apicontext.New(ctx).
		WithOffset(*offset).
		WithLimit(*limit).
		Context

	return tivo.GetShows(ctx, obj)
}

// Tivo returns server.TivoResolver implementation.
func (r *Resolver) Tivo() server.TivoResolver { return &tivoResolver{r} }

type tivoResolver struct{ *Resolver }
