// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type Tivo struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Tsn     string `json:"tsn"`
}
